services:

  app:
    image: jar--${JAR_NAME}:release
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    env_file:
      - ./.env
    command: yarn start
    restart: unless-stopped
    ports:
      - ${APP_SERVICE_PORT}:3000
